# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update API package list
RUN apt-get update

# Upgrade all currently installed software
RUN apt-get upgrade -y

# Echo "Hello, World!" when the container starts
CMD ["echo", "Hello, World!"]